# Generated by Django 5.2.7 on 2025-10-12 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('estatus', models.CharField(default='Nuevo', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField()),
                ('creado_por', models.CharField(blank=True, max_length=100)),
                ('nuevo_estatus', models.CharField(blank=True, max_length=50)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='prospects.prospect')),
            ],
        ),
    ]
